#!/bin/bash

CURDIR=`pwd`

cd src/Mint-Y
./build-themes.py

pysassc ./gtk-3.0/sass/gtk.scss ./gtk-3.0/gtk.css
pysassc ./gtk-3.0/sass/gtk-dark.scss ./gtk-3.0/gtk-dark.css

cd $CURDIR

sudo rm -rf ~/.themes/OneDark
sudo cp -R usr/share/themes/Mint-Y-Dark ~/.themes/OneDark

# Force refresh
gsettings set org.cinnamon.desktop.interface gtk-theme 'Cinnamon'
gsettings set org.cinnamon.theme name 'Mint-Y-Dark'
gsettings set org.cinnamon.desktop.interface gtk-theme 'OneDark'
gsettings set org.cinnamon.theme name 'OneDark'
